# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.

twitter: computerhacking101
#weibo: yourweibousername
#zhihu: yourzhihuusername
#reddit: yourredditusername
#telegram: yourtelegramusername
dockerhub: mcncyo
#medium: yourmediumusername # Medium username or custom domain(e.g. https://custom.domain.tld).
#bilibili: yourbilibiliuserid
youtube: UCWbsbHA8HwFB1eBf-XQh6Zw
#discord: yourdiscordinvitecode
#discourse: https://yourforum.tld
#facebookgroup: yourfacebookgroupname
github: mcncyo
#pinterest: yourpinterestusername
#mastodon: yourmastodonusername
paypal: mcncyo
patreon: Computerhacking101

